### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by polluks** [0xC0DE6502/manic-miner-2021-releases#1]
What about the source code? For the sake of completeness.

**Comment by 0xC0DE6502** [comment]
Electron specific source code is unpublished, but it is based on the [BBC Micro source code](https://github.com/TobyLobster/ManicMiner2021)

**Comment by polluks** [comment]
I was asking because of this issue https://github.com/TomHarte/CLK/issues/1390.
Maybe interrupts are not correctly implemented.

**Comment by 0xC0DE6502** [comment]
I have just tried playing Manic Miner with clksignal on Ubuntu and noticed nothing out of the ordinary. Have you tried the other disk image of Manic Miner? The clksignal screen is always a bit wobbly for me, but I always figured that is the interlace effect being simulated (?)

**Comment by polluks** [comment]
At least my Mac has this issue. Thank you so far.

**Comment by polluks** [comment]
FYI emulation bug fixed.

**Comment by 0xC0DE6502** [comment]
Thanks for letting me know!
